
// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	dtos "BookingSystem/Booking/internal/dtos"
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "BookingSystem/Booking/internal/models"

	time "time"
)

// UserRepositoryMock is an autogenerated mock type for the UserRepositoryInterface type
type UserRepositoryMock struct {
	mock.Mock
}

// CheckRoomAvailability provides a mock function with given fields: ctx, roomID, start, end
func (_m *UserRepositoryMock) CheckRoomAvailability(ctx context.Context, roomID uint, start time.Time, end time.Time) (bool, string) {
	ret := _m.Called(ctx, roomID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for CheckRoomAvailability")
	}

	var r0 bool
	var r1 string
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, time.Time) (bool, string)); ok {
		return rf(ctx, roomID, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, time.Time) bool); ok {
		r0 = rf(ctx, roomID, start, end)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, time.Time, time.Time) string); ok {
		r1 = rf(ctx, roomID, start, end)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// CheckRoomAvailabilityForUpdate provides a mock function with given fields: ctx, roomID, start, end, bookingUUID
func (_m *UserRepositoryMock) CheckRoomAvailabilityForUpdate(ctx context.Context, roomID uint, start time.Time, end time.Time, bookingUUID string) bool {
	ret := _m.Called(ctx, roomID, start, end, bookingUUID)

	if len(ret) == 0 {
		panic("no return value specified for CheckRoomAvailabilityForUpdate")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, time.Time, string) bool); ok {
		r0 = rf(ctx, roomID, start, end, bookingUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CreateBooking provides a mock function with given fields: ctx, booking
func (_m *UserRepositoryMock) CreateBooking(ctx context.Context, booking *models.Booking) *dtos.Error {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 *dtos.Error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Booking) *dtos.Error); ok {
		r0 = rf(ctx, booking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.Error)
		}
	}

	return r0
}

// GetBookingByUUID provides a mock function with given fields: ctx, uuid
func (_m *UserRepositoryMock) GetBookingByUUID(ctx context.Context, uuid string) (*models.Booking, *dtos.Error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByUUID")
	}

	var r0 *models.Booking
	var r1 *dtos.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Booking, *dtos.Error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Booking); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *dtos.Error); ok {
		r1 = rf(ctx, uuid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dtos.Error)
		}
	}

	return r0, r1
}

// GetCustomerByUUID provides a mock function with given fields: ctx, uuid
func (_m *UserRepositoryMock) GetCustomerByUUID(ctx context.Context, uuid string) (*models.Customer, *dtos.Error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerByUUID")
	}

	var r0 *models.Customer
	var r1 *dtos.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Customer, *dtos.Error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Customer); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *dtos.Error); ok {
		r1 = rf(ctx, uuid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dtos.Error)
		}
	}

	return r0, r1
}

// GetRoomByUUID provides a mock function with given fields: ctx, uuid
func (_m *UserRepositoryMock) GetRoomByUUID(ctx context.Context, uuid string) (*models.Room, *dtos.Error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByUUID")
	}

	var r0 *models.Room
	var r1 *dtos.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Room, *dtos.Error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Room); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *dtos.Error); ok {
		r1 = rf(ctx, uuid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dtos.Error)
		}
	}

	return r0, r1
}

// SoftDeleteBooking provides a mock function with given fields: ctx, bookingUUID
func (_m *UserRepositoryMock) SoftDeleteBooking(ctx context.Context, bookingUUID string) *dtos.Error {
	ret := _m.Called(ctx, bookingUUID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteBooking")
	}

	var r0 *dtos.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) *dtos.Error); ok {
		r0 = rf(ctx, bookingUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.Error)
		}
	}

	return r0
}

// UpdateBooking provides a mock function with given fields: ctx, booking
func (_m *UserRepositoryMock) UpdateBooking(ctx context.Context, booking *models.Booking) *dtos.Error {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBooking")
	}

	var r0 *dtos.Error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Booking) *dtos.Error); ok {
		r0 = rf(ctx, booking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.Error)
		}
	}

	return r0
}

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
