
// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	dtos "BookingSystem/Booking/internal/dtos"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserServiceMock is an autogenerated mock type for the UserServiceInterface type
type UserServiceMock struct {
	mock.Mock
}

// CreateBooking provides a mock function with given fields: ctx, req, requestID
func (_m *UserServiceMock) CreateBooking(ctx context.Context, req dtos.BookingRequest, requestID string) *dtos.APIResponse {
	ret := _m.Called(ctx, req, requestID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 *dtos.APIResponse
	if rf, ok := ret.Get(0).(func(context.Context, dtos.BookingRequest, string) *dtos.APIResponse); ok {
		r0 = rf(ctx, req, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.APIResponse)
		}
	}

	return r0
}

// DeleteBooking provides a mock function with given fields: ctx, bookingUUID, requestID
func (_m *UserServiceMock) DeleteBooking(ctx context.Context, bookingUUID string, requestID string) *dtos.APIResponse {
	ret := _m.Called(ctx, bookingUUID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBooking")
	}

	var r0 *dtos.APIResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dtos.APIResponse); ok {
		r0 = rf(ctx, bookingUUID, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.APIResponse)
		}
	}

	return r0
}

// GetBookingByID provides a mock function with given fields: ctx, bookingUUID, requestID
func (_m *UserServiceMock) GetBookingByID(ctx context.Context, bookingUUID string, requestID string) *dtos.APIResponse {
	ret := _m.Called(ctx, bookingUUID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByID")
	}

	var r0 *dtos.APIResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dtos.APIResponse); ok {
		r0 = rf(ctx, bookingUUID, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.APIResponse)
		}
	}

	return r0
}

// UpdateBooking provides a mock function with given fields: ctx, bookingUUID, req, requestID
func (_m *UserServiceMock) UpdateBooking(ctx context.Context, bookingUUID string, req dtos.BookingRequest, requestID string) *dtos.APIResponse {
	ret := _m.Called(ctx, bookingUUID, req, requestID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBooking")
	}

	var r0 *dtos.APIResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, dtos.BookingRequest, string) *dtos.APIResponse); ok {
		r0 = rf(ctx, bookingUUID, req, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.APIResponse)
		}
	}

	return r0
}

// NewUserServiceMock creates a new instance of UserServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceMock {
	mock := &UserServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

